const data = [{
        id: 'best-01',
        price: 110000,
        title: "SNOWMAN15 Portable Stand",
        style: "IK Table 시리즈",
        desc: "IK만의 오리지널 디자인을 품고 있는 일광전구의 첫 번째 무선 조명",
        image: process.env.PUBLIC_URL + '/images/sub01.jpg',
    },
    {
        id: 'best-02',
        price: "340,000",
        title: "SWAN2 Floor Stand",
        style: "IK Floor 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub02.jpg",
    },
    {
        id: 'best-03',
        price: 240000,
        title: "SWAN2 Table Stand",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub03.jpg",
    },
    {
        id: 'best-04',
        price: 290000,
        title: "PINOCCHIO120 A Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub04.jpg",
    },
    {
        id: 'best-05',
        price: 280000,
        title: "PINOCCHIO120 B Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub05.jpg",
    },
    {
        id: 'best-06',
        price: 190000,
        title: "WORKSHOP38 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub06.jpg",
    },
    {
        id: 'best-07',
        price: 150000,
        title: "WORKSHOP28 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub07.jpg",
    },
    {
        id: 'best-08',
        price: 120000,
        title: "WORKSHOP18 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub08.jpg",
    },
    {
        id: 'best-09',
        price: 230000,
        title: "SNOWMAN22 SOLID Table Stand",
        style: "IK Table 시리즈",
        desc: "상단의 납작한 눈사람의 모습과 닮은 22cm의 둥글고 부드러운 형태",
        image: process.env.PUBLIC_URL+"/images/sub09.jpg",
    },
    {
        id: 'best-10',
        price: 210000,
        title: "SNOWBALL22 SOLID Table Stand",
        style: "IK Table 시리즈",
        desc: "상단의 22cm의 둥글고 부드러운 형태의 유리구가 돋보이는 스탠드",
        image: process.env.PUBLIC_URL+"/images/sub10.jpg",
    },
    {
        id: 'best-11',
        price: 280000,
        title: "FONDUE16 Table Stand KYOBO BOOK Edition",
        style: "IK Table 시리즈",
        desc: "일광전구와 교보문고가 협업하여 완성한 테이블 스탠드",
        image: process.env.PUBLIC_URL+"/images/sub11.jpg",
    },
    {
        id: 'best-12',
        price: 390000,
        title: "TRIANGLE120 A Pendant",
        style: "IK Pendant 시리즈",
        desc: "삼각형이 가지고 있는 조형적 특성을 모티브로 디자인적인 위트와 구조적으로 강력한 내구성을 함께 가지고 있는 조명",
        image: process.env.PUBLIC_URL+"/images/sub12.jpg",
    },
    {
        id: 'best-13',
        price: 390000,
        title: "TRIANGLE120 B Pendant",
        style: "IK Pendant 시리즈",
        desc: "삼각형이 가지고 있는 조형적 특성을 모티브로 디자인적인 위트와 구조적으로 강력한 내구성을 함께 가지고 있는 조명",
        image: process.env.PUBLIC_URL+"/images/sub13.jpg",
    },
    {
        id: 'best-14',
        price: 360000,
        title: "TRIANGLE120 C Pendant",
        style: "IK Pendant 시리즈",
        desc: "삼각형이 가지고 있는 조형적 특성을 모티브로 디자인적인 위트와 구조적으로 강력한 내구성을 함께 가지고 있는 조명",
        image: process.env.PUBLIC_URL+"/images/sub14.jpg",
    },
    {
        id: 'best-15',
        price: 110000,
        title: "TRIANGLE120 PANEL A",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub15.jpg",
    },
    {
        id: 'best-16',
        price: 110000,
        title: "TRIANGLE120 PANEL B",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub16.jpg",
    },
    {
        id: 'best-17',
        price: 80000,
        title: "TRIANGLE120 PANEL C",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub17.jpg",
    },
    {
        id: 'best-18',
        price: 380000,
        title: "MAGRITTE40 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub18.jpg",
    },
    {
        id: 'best-19',
        price: 280000,
        title: "MAGRITTE25 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub19.jpg",
    },
    {
        id: 'best-20',
        price: 290000,
        title: "SLOPE45 SMART Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub20.jpg",
    },
    {
        id: 'best-21',
        price: 340000,
        title: "B-DAY45 Pendant",
        style: "IK Pendant 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub21.jpg",
    },
    {
        id: 'best-22',
        price: 340000,
        title: "APOLLO22 Table Stand",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub22.jpg",
    },
    {
        id: 'best-23',
        price: 180000,
        title: "TALLBOY16 Table Stand",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub23.jpg",
    },
    {
        id: 'best-24',
        price: 200000,
        title: "SNOWBALL22 Table Stand",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub24.jpg",
    },
    {
        id: 'best-25',
        price: 220000,
        title: "SNOWMAN22 Table Stand",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub25.jpg",
    },
    {
        id: 'best-26',
        price: 320000,
        title: "SNOWBALL22 Floor Stand",
        desc: "IK Floor 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub26.jpg",
    },
    {
        id: 'best-27',
        price: 340000,
        title: "SNOWMAN22 Floor Stand",
        desc: "IK Floor 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub27.jpg",
    },
    {
        id: 'best-28',
        price: 170000,
        title: "FROG22 Table Stand White Edition",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub28.jpg",
    },
    {
        id: 'best-29',
        price: 170000,
        title: "ACORN22 Table Stand White Edition",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub29.jpg",
    },
    {
        id: 'best-30',
        price: 270000,
        title: "ACORN22 Floor Stand",
        style: "IK Floor 시리즈",
        desc: "IK Floor 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub30.jpg",
    },
    {
        id: 'best-31',
        price: 310000,
        title: "ACORN38 Floor Stand",
        style: "IK Floor 시리즈",
        desc: "IK Floor 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub31.jpg",
    },
    {
        id: 'best-32',
        price: 270000,
        title: "FROG22 Floor Stand",
        style: "IK Floor 시리즈",
        desc: "IK Floor 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub32.jpg",
    },
    {
        id: 'best-33',
        price: 310000,
        title: "FROG38 Floor Stand",
        style: "IK Floor 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub33.png",
    },
    {
        id: 'best-34',
        price: 890000,
        title: "LANDSCAPE68 Table Stand Industrial Gray",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub34.jpg",
    },
    {
        id: 'best-35',
        price: 890000,
        title: "LANDSCAPE68 Table Stand Aluminium",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub35.jpg",
    },
    {
        id: 'best-36',
        price: 240000,
        title: "SWAN Table Stand ODENSE Edition",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub36.jpg",
    },
    {
        id: 'best-37',
        price: 55000,
        title: "CANDLE9 Table Stand White",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub37.jpg",
    },
    {
        id: 'best-38',
        price: 55000,
        title: "CANDLE9 Table Stand Mint",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub38.jpg",
    },
    {
        id: 'best-39',
        price: 55000,
        title: "CANDLE9 Table Stand Ivory & Green",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub39.jpg",
    },
    {
        id: 'best-40',
        price: 55000,
        title: "CANDLE9 Table Stand Burgundy",
        style: "IK Table 시리즈",
        desc: "IK 시리즈",
        image: process.env.PUBLIC_URL+"/images/sub40.jpg",
    },
]

export default data;